export const HOTELS_REQUEST = 'HOTELS_REQUEST';
export const HOTELS_ERROR = 'HOTELS_ERROR';
export const HOTELS_SUCCESS = 'HOTELS_SUCCESS';
export const UPDATE_OPTION = 'UPDATE_OPTION';
export const ADD_NEW_LIKED = 'ADD_NEW_LIKED';
export const REMOVE_LIKED = 'REMOVE_LIKED';
